FROM golang:alpine

RUN apk --no-cache add vim nano bash git \
    && echo go-crond examples/crontab >> /root/.ash_history \
    && echo go-crond --system-defaults >> /root/.ash_history

RUN go get github.com/robfig/cron
RUN go get github.com/jessevdk/go-flags

COPY . /go/src/go-crond
WORKDIR /go/src/go-crond

RUN go build \
    && cp -a go-crond /usr/local/bin

CMD ["./go-crond"]
