name: "Release: assets"

on:
  release:
    types: [created]

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set Swap Space
        uses: pierotofy/set-swap-space@master
        with:
          swap-size-gb: 12

      - uses: actions/setup-go@v2
        with:
          go-version: '1.19'
          check-latest: true

      - name: Build
        run: |
          make release-assets

      - name: Upload assets to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ./release-assets/*
          tag: ${{ github.ref }}
          overwrite: true
          file_glob: true
